version: '3.8'

services:
  goalee-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: goalee-calorie-tracker

  # Development service (optional)
  goalee-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev 